/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // defaultSidebar: [{type: 'autogenerated', dirName: '.', }],
  hamsterSidebar: [
    'index',
    {
      type: 'category',
      label: 'Introduction',
      collapsible: true,
      collapsed: true,
      items: ['intro'],
    },
    {
      type: 'category',
      label: 'Quick Access',
      collapsible: true,
      collapsed: true,
      items: ['quickaccess/User', 'quickaccess/Provider'],
    },
    {
      type: 'category',
      label: 'Terminology',
      collapsible: true,
      collapsed: true,
      items: ['explanation'],
    },
  ],
}

module.exports = sidebars
