name: GitBook action
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run : |
          docker build -t hamstershare/hamster-gitbook:latest .
          docker push hamstershare/hamster-gitbook:latest
  deploy:
    needs:
      - docker-build
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy portal
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HAMSTER_SERVER_HOST }}
          username: ${{ secrets.HAMSTER_SERVER_USERNAME }}
          key: ${{ secrets.HAMSTER_SERVER_KEY }}
          port: ${{ secrets.HAMSTER_SERVER_PORT }}
          script: |
            cd /root/hamster-deploy
            docker compose pull
            docker compose up -d
